### ISSUE TITLE
cabal install --only-dep fails

### ISSUE THREAD

**Issue by Mr-Click** [pfq/PFQ#10]
Hi all,

I am trying to install PFQ framework but the command `cabal install --only-dep` on PFQ/ gives me the following output:

Reading available packages...
Choosing modular solver.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: pfq-framework-4.4 (user goal)
trying: base-4.8.1.0/installed-206... (dependency of pfq-framework-4.4)
next goal: here (dependency of pfq-framework-4.4)
rejecting: here-1.2.7 (global constraint requires ==1.2.6)
rejecting: here-1.2.6 (conflict: base==4.8.1.0/installed-206..., here =>
base>=4.5 && <4.8)
rejecting: here-1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2, 1.1, 1.0 (global
constraint requires ==1.2.6)
Dependency tree exhaustively searched.

what am I missing?

best regards,
Valerio

**Comment by pfq** [comment]
Please, could you tell me which Linux distribution, ghc compiler are you using?

**Comment by valerio-click** [comment]
I'm using Debian Jessie with ghc version 7.10. If I run cabal with file cabal.config.7.10, I get what follows:

$ cabal --config-file=cabal.config.7.10 install --only-dep
Warning: /home/pc01/PFQ/cabal.config.7.10: Unrecognized field constraints on
line 5
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: pfq-framework-4.4 (user goal)
next goal: here (dependency of pfq-framework-4.4)
rejecting: here-1.2.7/installed-3c8... (global constraint requires ==1.2.6)
Dependency tree exhaustively searched.

**Comment by valerio-click** [comment]
As a minor issue I noticed that in pfq.h (line 237) there is a typo in the prototype of pfq_open which is
extern pfq_t* pfq_open(size_t calpen, size_t slots);

while it should be:
extern pfq_t* pfq_open(size_t caplen, size_t slots);

best regards,
Valerio

**Comment by awgn** [comment]
The cabal.config shipped for GHC 7.10 is probably outdated.
Consider using the nightly build available from https://www.stackage.org/nightly/cabal.config
I'm going to add a README about it (and remove the cabal.config.7.10).

**Comment by valerio-click** [comment]
Hi,

I was trying to install PFQ from scratch on a Debian Jessie with GHC 7.10.
In installing PFQ dependencies I run into the following constraint conflict:

- to install storablevetor it seems I need syb package installed with version >=0.1 and <0.5
- however, packages here-1.2.7 haskell-src-meta-0.6.0.10 th-orphans-0.12.2 th-reify-many-0.1.3 th-expand-syns-0.3.0.6 (which have been installed to solve some other PFQ dependencies) require syb-0.5.1.

any idea on how to tackle this?

PS: I'm using cabal nightly build
PSS: Technically, would it make sens to ship PFQ with a package containing all haskell dependencies? This could help in promoting the use of PFQ also for those that are not confident with haskell package system.

Thanks and regards,
Valerio

**Comment by valerio-click** [comment]
OK I managed to install all dependencies with cabal. I have to say that I am not at all expert with Haskell but the installation procedure has been quite awkward. Apparently, cabal behavior in installing external packages is strictly dependent on weather you run it inside a project (in this case PFQ) or not.
There are roughly the steps I made (on Debian jessie stable 8.1):

STEP 1:
install ghc 7.10 form the experimental repo

STEP 2:
apt-get install linux-headers-$(uname -r)
apt-get install cmake

STEP 3 (rigorously outside PFQ directory):
cabal install --allow-newer=base alex happy -j3

STEP 4 (inside PFQ directory):
cabal install --allow-newer=base --only-dep -j3
At the end of it I got the following error message
Preprocessing library storablevector-0.2.10...

src/Data/StorableVector/Base.hs:60:8:
    Could not find module ‘Data.Generics’
    It is a member of the hidden package ‘syb-0.5.1@syb_8qmIMcBFhWM7BKRUTFb5M4’.
    Perhaps you need to add ‘syb’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘syb-0.4.4@syb_HXdJjHFXhlk7hr6SnBkoe9’.
    Perhaps you need to add ‘syb’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
storablevector-0.2.10 failed during the building phase. The exception was:
ExitFailure 1

STEP 5 (inside PFQ directory)
I run "runhaskell Build.hs configure" and got an error during the building of pfq-haskell-lib as follows:

[1/1] Building pfq-haskell-lib:
\# Satisfying dependencies for Building pfq-haskell-lib...
Building pfq-4.4...
Preprocessing library pfq-4.4...
dist/build/Network/PFq_hsc_make: error while loading shared libraries: libpfq.so: cannot open shared object file: No such file or directory
running dist/build/Network/PFq_hsc_make failed (exit code 127)
command was: dist/build/Network/PFq_hsc_make  >dist/build/Network/PFq.hs
Error: Building pfq-haskell-lib aborted!

STEP 6:
due that at STEP 5 the building got stuck because it cannot find libpfq.so I run an "ldconfig" just to be on the safe side and then run again "runhaskell Build.hs configure" and got different error message on pfq-haskell-lib as follows:
[1/1] Building pfq-haskell-lib:
\# Satisfying dependencies for Building pfq-haskell-lib...
Building pfq-4.4...
Preprocessing library pfq-4.4...

dist/build/Network/PFq.hs:1:1:
    File name does not match module name:
    Saw: ‘Main’
    Expected: ‘Network.PFq’
Error: Building pfq-haskell-lib aborted!

STEP 7:
I run "runhaskell Build.hs clean" and then again "runhaskell Build.hs configure" and this time everything went smooth.

STEP 8:
I successfully run "runhaskell Build.hs build" and "runhaskell Build.hs install" 

I hope this list will help identifying a smoother way to get things up and running.

regards,
Valerio

**Comment by awgn** [comment]
Thanks for reporting this install issue. I'll try to fix it as soon as possible (basically when I'm back from vacation). 

In the meanwhile give a look at stackage site. The new LTS is compliant with GHC 7.10. (I'll update the install procedure)

Be aware that if you install packages outside the PFQ directory you use the default configuration for ghc and that explains the conflicts with stackage.

N.

**Comment by pfq** [comment]
ldconfig issue is fixed in PFQ 5.0 (experimental branch)! In addition, new the command of Build.hs distclean is available to clean up the whole project.
